### ISSUE TITLE
"there is a cycle" during Determinizing L*G

### ISSUE THREAD

**Issue by qssheep** [k2-fsa/snowfall#36]
I was trying the Librispeech example and got error when running decode.py

Loading L_disambig.fst.txt
Loading G.fsa.txt
DEBUG:root:Intersecting L and G
DEBUG:root:LG shape = (21246039, None)
DEBUG:root:Connecting L*G
DEBUG:root:LG shape = (21246039, None)
DEBUG:root:Determinizing L*G
[F] /home/yckj2113/github/k2/k2/csrc/host/fsa_util.cc:void k2host::CreateFsa(const std::vector<k2host::Arc>&, k2host::Fsa*, std::vector<int>*):470 there is a cycle: 15976413 -> 256

My lm was downloaded using run.sh.

**Comment by qindazhu** [comment]
I guess you are running with `G.fst.txt` you generated with old scripts in `snowfall` before, the cycle is from `</s>` (EOS) in LM. We have fixed that issue with https://github.com/k2-fsa/snowfall/pull/33, so just pull the latest code and re-generate `G.fst.txt` by running `run.sh` would be fine.

BTW, there's another issue in `decode.py` now about `aux_labels` on L*G, see here https://github.com/k2-fsa/snowfall/issues/31#issuecomment-738570169 for details, we need to write some C++ code to fix that issue, so the `decode.py` now is actually not working (the script is disabled in my last PR, but because of some reason, the change is not merged)

**Comment by qssheep** [comment]
Thank you, I'll try it as soon as decode.py is available.

**Comment by qssheep** [comment]
I tried the latest version today and the error still appears. 
Then I realized it is my k2 version instead of snowfal, after re-install my k2, this error disappears.

**Comment by qindazhu** [comment]
Thanks, bear in mind we are still tuning the model, so please ignore the bad WER for now (but definitely you can see the whole train/decoding process with k2 and lhotse)
